import logging

# Logger
LOGGER_LEVEL = logging.INFO

# Earth Engine API
EE_PROJECT_NAME = "gee-lab-2024"
GCS_BUCKET_NAME = "goodforest-lab"
CLEAR_CREDENTIALS = False

# General parameters
NB_S2_BANDS = 11
NB_VEGETATION_INDEXES = 13
NB_CHANNELS_WITHOUT_LABELS = NB_S2_BANDS + NB_VEGETATION_INDEXES
NB_CHANNELS_WITH_LABELS = NB_CHANNELS_WITHOUT_LABELS + 1
PERIOD_S2_IMAGES = 5

PIXEL_SIZE_METERS = 10
TILE_SIZE_KM = 110
TILE_OVERLAP_KM = 10

RANDOM_SEED = 42

# Sentinel-2 loading parameters
MAX_THRESHOLD_BLACK_PIXELS = 0.8
MAX_THRESHOLD_CLOUDY_PIXELS = 20
STEP_CLOUD_COVER = 1
SAVING_LOCATION = "local"

# Models parameters
CUBE_SIZE = 256
BORDER_EFFECT_PADDING = 30
OVERLAP_PREDICTION_SIZE = 3 * BORDER_EFFECT_PADDING
BUFFER_PREDICTION = CUBE_SIZE * PIXEL_SIZE_METERS
OVERLAP_PREDICTION_METERS = OVERLAP_PREDICTION_SIZE * PIXEL_SIZE_METERS

DEFAULT_INSECTS = ["IBM", "IBS", "IBB", "IBD", "IBL", "IBW", "IBF"]
SUFFIX_ANNOTATED = "annotated"
FILENAME_CUBES_FILE = "cubes"

BATCH_SIZE = 10
NB_EPOCHS = 200

# Fordead constants
FORDEAD_PERIOD_S2_IMAGES = 730

DEFAULT_COLORS_VISUALIZATION = "rgb"
DEFAULT_COMPRESSION = 512

# Clustering
ZONE_CLUSTER_SIZE = 10

# Visualization
DICT_CLS_COLOR_5_CLASSES = {
    "sain": "#1C5800",  # DarkGreen
    "T": "#B9FF00",  # GreenYellow
    "L": "#FFF700",  # Yellow
    "M": "#FF0000",  # Red
    "S+V": "#B5B5B5",  # Grey
    "fond + nuage": "black",
}
